### ISSUE TITLE
The requirement.txt is missing.

### ISSUE THREAD

**Issue by JieChen91** [Rentier/keras-autoencoder#1]
Hi, I want to run keras-autoencoder. But some bugs come out due to environment conflicts.
I cannot find the requirement.txt in the repository. Could you kindly push it?
Thanks~

**Comment by jcklie** [comment]
I fixed the installation, updated the README and added the requirement.txt. I am sorry for forgetting that, I hope it did not cause too many problems. If you have further questions, please do not hesitate to ask, I want to make this project more usable for other people, not just for me.
